homepage/urls.py
from django.urls import re_path
from . import views

app_name = 'homepage'

urlpatterns = [
	re_path(r'^$', views.homepage, name ='homepage'),
	re_path(r'^home/$', views.home, name='home'),
	re_path(r'^abilities/$', views.abilities, name = 'abilities'),
	re_path(r'^contact/$', views.contact, name='contact'),
	re_path(r'^education/$', views.education, name='education'),
	re_path(r'^experience/$', views.experience, name = 'experience'),
	re_path(r'^schedule/$', views.todo, name = 'schedule'),
	re_path(r'^send/$', views.send, name = 'send'),
	re_path(r'^(?P<id>[0-9]+)/delete_schedule/$', views.delete_schedule, name= 'delete_schedule')
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'))
]

homepage/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
	date = models.DateField()
	time = models.TimeField()
	where = models.TextField(null=True)
	category = models.TextField(null=True)
	todo = models.TextField()

			

homepage/views.py
from django.shortcuts import render
from .form import Add_TodoList
from .models import Todo
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from datetime import datetime
from django.shortcuts import get_object_or_404

response = {
	'nama' : 'Novia Ramadani'
}
# Create your views here.
def abilities(request):
	return render(request, 'Abilities.html')

def contact(request):
	return render(request, 'Contact.html')

def education (request):
	return render(request, 'Education.html')

def experience (request):
	return render(request, 'Experience.html')

def home(request):
	return render(request, 'home.html')

def homepage(request):
	return render(request, 'homepage.html')

def todo(request):
	Todolist = Todo.objects.all().values()
	response['Todolist'] = convert_queryset_into_json(Todolist)
	response['form'] = Add_TodoList

	return render(request, 'jadwal.html', response)

def send(request):
	form = Add_TodoList(request.POST)

	if request.method == 'POST' and form.is_valid():
		print(request.POST)
		date_converted = datetime.strptime(request.POST['date'], '%Y-%m-%d')
		time_converted = datetime.strptime(request.POST['time'], '%H:%M')
		log = Todo(date=date_converted, time=time_converted, where=request.POST['where'], category=request.POST['category'], todo=request.POST['todo'])
		log.save()

	return HttpResponseRedirect('/schedule/')
	
def convert_queryset_into_json(queryset):
    ret_val = []
    for data in queryset:
        ret_val.append(data)
    return ret_val

def delete_schedule(request, id=None):
	todoObject = get_object_or_404(Todo, pk=id)
	todoObject.delete()
	return HttpResponseRedirect('/schedule/')

homepage/templates/Abilities.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Novia Ramadani</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href= "{% static 'css/style.css' %}" />
	<link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>
	

</head>
<body>
	<div class="container">
		{% include "homepage/../navbar/navbar.html" %}
		
		<div id="box">
			<div id= "frame">
				<hr align="left">
				<h2>Abilities</h2>
			</div>
			
			<div id="text">
				<ul>
				    <li>
				    	<div id="ab">SKILL</div>
					        <div class="row justify-content-start">
					        	<div class="col-12 col-md-4">
							      Java
							    </div>
							    <div class="col">
							      <div class="w3-black" style="height:24px;width:64% ">80%</div>
							    </div>
							</div>
							<div class="row justify-content-start">
					        	<div class="col-12 col-md-4">
							      Phyton
							    </div>
							    <div class="col">
							      <div class="w3-black" style="height:24px;width:64%">80%</div>
							    </div>
							</div>
							<div class="row justify-content-start">
					        	<div class="col-12 col-md-4">
							      HTML
							    </div>
							    <div class="col">
							      <div class="w3-black" style="height:24px;width:64%">80%</div>
							    </div>
							</div>
							<div class="row justify-content-start">
					        	<div class="col-12 col-md-4">
							      Microsoft Office
							    </div>
							    <div class="col">
							      <div class="w3-black" style="height:24px;width:76%">95%</div>
							    </div>
							</div>
					</li>
					
				    <li>
				    	<div id="ab">Expertise</div>
					        <div class="row justify-content-start">
					        	<div class="col-12 col-md-4">
							      Programming
							    </div>
							    <div class="col">
							      <div class="w3-black" style="height:24px;width:64%">80%</div>
							    </div>
							</div>
							<div class="row justify-content-start">
					        	<div class="col-12 col-md-4">
							     	Financial Management
							    </div>
							    <div class="col">
							      <div class="w3-black" style="height:24px;width:76%">95%</div>
							    </div>
							</div>
							<div class="row justify-content-start">
					        	<div class="col-12 col-md-4">
							      Time Management
							    </div>
							    <div class="col">
							      <div class="w3-black" style="height:24px;width:76%">95%</div>
							    </div>
							</div>
					</li>
					<li>
						<div id="ab">Expertise</div>
							<div class="row justify-content-start">
					        	<div class="col-12 col-md-4">
							      Indonesia
							    </div>
							    <div class="col">
							      <div class="w3-black" style="height:24px;width:80%">100%</div>
							    </div>
							</div>
							<div class="row justify-content-start">
					        	<div class="col-12 col-md-4">
							     	English
							    </div>
							    <div class="col">
							      <div class="w3-black" style="height:24px;width:72%">90%</div>
							    </div>
							</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</body>
</html>

homepage/templates/Contact.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Novia Ramadani</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
	<div class="container">
		{% include "homepage/../navbar/navbar.html" %}
		
		<div id="box">
			<div id= "frame">
				<hr align="left">
				<h2>Contact</h2>
			</div>

			<div id="text">
				<div id="sosmed">
					<div class="row mx-lg">
						<div class="col-12 col-md">
							<ul>
							    <li>
							    	<a href="https://mail.google.com/" class="fa fa-envelope"> &nbsp &nbsp noviaramadani0@gmail.com</a>
							    </li>
							    <li>
							    	<a href="https://instagram.com/noviarmdnfg" class="fa fa-instagram"> &nbsp&nbsp &nbsp noviarmdnfg</a>
							    </li>
							</ul>
						</div>
						<div class="col-12 col-md">
							<ul>
							    <li>
							    	<a href="https://twitter.com/novyarama" class="fa fa-twitter"> &nbsp &nbsp novyarama</a>
							    </li>
							    <li>
							    	<a href="https://www.linkedin.com/in/novia-ramadani-90aaa9171/" class="fa fa-linkedin"> &nbsp &nbsp Novia Ramadani</a>
							    </li>
							</ul>						
						</div>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</body>
</html>

homepage/templates/Education.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Novia Ramadani</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>

</head>
<body>
	<div class="container">
		{% include "homepage/../navbar/navbar.html" %}
		
		<div id="box">
			<div id= "frame">
				<hr align="left">
				<h2>Education</h2>
			</div>
			
		
			<div id="text">
				<ul>
				    <li>
				    	<div id= "kuliah">
							<div id="sekolah">
								<p>Universitas Indonesia</p>	
							</div>
							<div id="lama">
								<p>Faculty Of Computer Science <br>Majoring in Information System<br>2018 - now </p>
							</div>
						</div>
				    </li>
				    <li>
				    	<div id="SMA">
							<div id="sekolah">
								<p>SMA Negeri 6 Prabumulih</p>
							</div>
							<div id="lama">
								<p>2015 - 2018</p>
							</div>
						</div>
				    </li>
				    <li>
				    	<div id="SMP">
							<div id="sekolah">
								<p>MTS Negeri 1 Prabumulih</p>
							</div>
							<div id="lama">
								<p>2012 - 2015</p>
							</div>
						</div>
				    </li>
				    <li>
				    	<div id="SD">
							<div id="sekolah">
								<p>SD Negeri 23 Prabumulih</p>
							</div>
							<div id="lama">
								<p>2006 - 2012</p>
							</div>
						</div>
				    </li>
				</ul>
			</div>
		</div>
		
	</div>
</body>
</html>

homepage/templates/Experience.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Novia Ramadani</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>

</head>
<body>
	<div class = "container">
		{% include "homepage/../navbar/navbar.html" %}

		<div id="box">
			<div id= "frame">
				<hr align="left">
				<h2>Experience</h2>
			</div>
			
			<div id="text">
				<div class="row mx-lg">
					<div class="col-12 col-md-6">
						<ul>
						    <li>
						    	<div id="jabatan">
						    		<p>Controller</p>
						    	</div>
						    	<div id="Organisasi">
						    		<p>DPM Fasilkom UI</p>
						    	</div>
						    </li>
						    
						    <li>
						    	<div id="jabatan">
						    		<p>Staff of FUKICorp</p>
						    	</div>
						    	<div id="Organisasi">
						    		<p>FUKI Fasilkom UI</p>
						    	</div>
						    </li>
						    <li>
						    	<div id="jabatan">
						    		<p>Staff of Medical Division</p>
						    	</div>
						    	<div id="Organisasi">
						    		<p>PMB Fasilkom UI</p>
						    	</div>
						    </li>
						</ul>
					</div>

					<div class="col-12 col-md-6">
						<ul>
							<li>
						    	<div id="jabatan">
						    		<p>1st Treasurer</p>
						    	</div>
						    	<div id="Organisasi">
						    		<p>Syukuran Wisuda Genap Fasilkom UI</p>
						    	</div>
						    </li>
						    <li>
						    	<div id="jabatan">
						    		<p>Coordinator of Prabumulih Region</p>
						    	</div>
						    	<div id="Organisasi">
						    		<p>Toska KEMAS UI</p>
						    	</div>
						    </li>
						    <li>
						    	<div id="jabatan">
						    		<p>Staff of Consumption Division</p>
						    	</div>
						    	<div id="Organisasi">
						    		<p>Universiade UI</p>
						    	</div>
						    </li>				    
						</ul>
					</div>
				</div>
			</div>
		</div>		

	</div>
</body>
</html>

homepage/templates/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Novia Ramadani</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>

</head>
<body>
	<div class = "container">
		{% include "homepage/../navbar/navbar.html" %}
		<div id="cont">
			<div class = "row mx-lg-n5" >
				<div class="col-12 col-md-5 py-3">
					<img id= "foto" src="{% static 'images/IMG_20180721_205549.jpg' %}" class="img-fluid" width="250px"> 
				</div>
				
				<div class="col-12 col-md-6 py-3 px-lg-5">
					<div id= "about">
						<hr align="left">
						<h2>About Me</h2>
					</div>

					<div id="tulisan">
					<p>Hi! I'm Novia Ramadani. I'm a Computer Science student at Universitas Indonesia class of 2018. I have an interest in learning about computers, technology and business. I'm a responsible person, can work with the team and fast respon. I'm a person who like to learn new things. I also have organizational experience, leadership and time management.</p>
					</div>
				</div>
			</div>
		</div>

	</div>
</body>
</html>

homepage/templates/homepage.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Novia Ramadani</title>
        <meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
		<link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>
    </head>
    <body>
        <div class="container2">
			<div id="homepage">
				<div class="row mx-lg">
					<div class="col-md-6 col-12">
						<div id="teks">
							<div id = "hi">
								<h6>Hello, I'm</h6>
							</div>
							<div id="nama">
								NOVIA RAMADANI
							</div>
							<div id="cs">
								A Computer Science Student
							</div>
							<div id="tombol">
								<a href="{% url 'homepage:home' %}">View Resume</a>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-12" id="ava">
						<img id="imgs" src="{% static 'images/ava.png' %}" class="img-fluid" width="400px"  alt="novia">
					</div>
				</div>
			</div>
		</div>
    </body>
</html>

homepage/templates/jadwal.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Novia Ramadani</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>

</head>
<body>
	<div class = "container">
		{% include "homepage/../navbar/navbar.html" %}

		<div id="box">
			<div id= "frame">
				<hr align="left">
				<h2>My Schedule</h2>
			</div>
			
			<div id="text">
				<div class="row mx-lg">
					<div class="col-12 col-md-6">
						<table class="table table-borderless">
						  <thead>
						    <tr>
						      <th scope="col">Date</th>
						      <th scope="col">Time</th>
						      <th scope="col">Place</th>
						      <th scope="col">Category</th>
						      <th scope="col">To Do</th>
						      <th scope="col"></th>
						    </tr>
						  </thead>
						  <tbody>
						    <tr>
								{% for todos in Todolist %}
									<td class="date"> {{ todos.date }} </td>
						      		<td class="time"> {{ todos.time }} </td>
						      		<td class="where">{{ todos.where }}</td>
						      		<td class="category">{{ todos.category }}</td>
						      		<td class="todo"> {{ todos.todo }} </td>
						      		<td><form action="{% url 'homepage:delete_schedule' todos.id %}" method="GET">
  									<button type="submit" class="btn btn-primary">Delete</button>
								  	</form>
							 		</td>
						    </tr>
						    {% endfor %}
						  </tbody>
						</table>
					</div>

					<div class="col-12 col-md-6">
						<form method="POST" action="{% url 'homepage:send' %}">
							{% csrf_token %}
							{{ form }}
						  
						  <button type="submit" class="btn btn-primary">Submit</button>
						</form>
					</div>
				</div>
			</div>
		</div>		

	</div>
</body>
</html>

homepage/templates/navbar/navbar.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head> 
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>

</head>
<body>
		<nav class="navbar navbar-expand-lg navbar-light">
		  <a class="navbar-brand" href="{% url 'homepage:homepage' %}">
		  <img src="{% static 'images/nama.png' %}" width="150px" class="img-fluid" alt="noviarmdnfg"></a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav">
			      <li class="nav-item">
			      	<a class="nav-link" href="{% url 'homepage:home' %}">About<span class="sr-only">(current)</span></a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'homepage:education' %}">Education</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'homepage:experience' %}">Experience</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'homepage:abilities' %}">Abilities</a>
			      </li>
			      <li class="nav-item">
			      	<a class="nav-link" href="{% url 'homepage:schedule' %}">Schedule</a>
			      </li>
			      <li class="nav-item">
			      	<a class="nav-link" href="{% url 'homepage:contact' %}" tabindex="-1" aria-disabled="true">Contact</a>
			      </li>
			    </ul>
		  </div>
		</nav>
</body>